"""Bookings microservice 0.2

Revision ID: dad70b686be0
Revises: 
Create Date: 2023-03-15 18:45:53.744877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad70b686be0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('facilityId', sa.Integer(), nullable=False),
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.Date(), nullable=False),
    sa.Column('bookingDate', sa.Date(), nullable=False),
    sa.Column('bookingTime', sa.Time(), nullable=False),
    sa.Column('bookingLength', sa.Time(), nullable=False),
    sa.Column('bookingEndTime', sa.Time(), nullable=False),
    sa.Column('bookingType', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
