"""Adding sale date

Revision ID: e69c60fd5ef7
Revises: 
Create Date: 2023-03-31 03:23:49.682551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69c60fd5ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SaleVal', sa.Float(), nullable=False),
    sa.Column('Facilityid', sa.Integer(), nullable=False),
    sa.Column('Activityid', sa.Integer(), nullable=False),
    sa.Column('SaleDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
