<div class="flex flex-col w-full px-8">
    <div>
        <h2 class="px-40 my-10 text-[48px] font-bold">Group Activities</h2>
    </div>
    <div class="flex flex-row w-full px-40 py-20">
        <div class="flex flex-1 flex-col items-start space-y-4 px-10">
            <h4 class="text-[34px] font-bold">Pilates</h4>
            <!-- description text generated by chatGPT-->
            <p>
                Pilates is a form of exercise that focuses on developing
                strength, flexibility, balance, and coordination through
                controlled movements, emphasizing the use of deep core muscles
                and breath. It improves physical function, reduces pain, and
                enhances overall well-being.
            </p>
            <img
                src="Pilates.webp"
                class="block w-full rounded-xl"
                alt="Pilates"
            />
        </div>
        <div class="flex flex-1 flex-col items-start space-y-4 px-10">
            <img src="studio.webp" class="block w-full rounded-xl" alt="Yoga" />
            <h4 class="text-[34px] font-bold">Yoga</h4>
            <!-- description text generated by chatGPT-->
            <p>
                Yoga is a mind-body practice from ancient India that involves
                physical postures, breath control, meditation, and relaxation
                techniques to promote physical and mental well-being, reduce
                stress, and improve flexibility, strength, balance, and posture.
            </p>
        </div>
    </div>
</div>
